#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --experimental-backends &
# pgrep -x xfce4-notifyd > /dev/null || /usr/lib/xfce4/notifyd/xfce4-notifyd &
pgrep -x dunst > /dev/null || dunst &
# pgrep -x xfce4-power-man > /dev/null || xfce4-power-manager &
pgrep -x nm-applet > /dev/null || nm-applet --indicator &
# pgrep -x pa-applet > /dev/null || pa-applet &
# pgrep -x kdeconnectd > /dev/null || kdeconnectd &
# pgrep -x kdeconnect-indi > /dev/null || kdeconnect-indicator &
pgrep -x polybar > /dev/null || $HOME/.config/bspwm/launch_ewmh.sh
# pgrep -x bspswallow > /dev/null || $HOME/.local/bin/bspswallow &
pgrep -f power-profiles-applet > /dev/null || power-profiles-applet &

# $HOME/.local/bin/mouseconfigure.sh

setxkbmap -option caps:escape
wmname LG3D


if [ $(xrandr | grep -sw 'connected' | wc -l) = 2 ]
then
    bspc wm --reorder-monitors DP-0 DP-2
    bspc monitor DP-0 -d 11 12 13 14 15 16 17 18 19
    bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
    bspc config pointer_follows_focus  true
else
    bspc monitor DP-0 --remove
    bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9

    bspc config pointer_follows_focus  false
fi

bspc config border_width           0
#bspc config window_gap             4
bspc config window_gap             0

bspc config split_ratio            0.50
#bspc config single_monocle         true
bspc config single_monocle         false
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer  true
# bspc config pointer_follows_focus  false
# bspc config normal_border_color    "#2e3440"
# bspc config active_border_color    "#2e3440"
# bspc config focused_border_color   "#5e81ac"
# bspc config presel_feedback_color  "#88c0d0"
bspc config normal_border_color    "#1e1e2e"
bspc config active_border_color    "#1e1e2e"
# bspc config focused_border_color   "#82aaff"
# bspc config focused_border_color   "#89ddff"
# bspc config presel_feedback_color  "#89ddff"
bspc config focused_border_color   "#89dceb"
bspc config presel_feedback_color  "#89dceb"
# bspc config ignore_ewmh_focus      true

bspc rule -a Emacs state=tiled
bspc rule -a Gcolor3 state=floating
bspc rule -a zoom state=floating
bspc rule -a QjackCtl state=floating
bspc rule -a slm state=floating
bspc rule -a Postman state=floating
bspc rule -a Picket state=floating
